### ISSUE TITLE
attribute writer, value seems undefined

### ISSUE THREAD

**Issue by GDmac** [fruux/sabre-xml-atom#3]
I am looking at using this package as a basis to read/write mRSS feeds.
Not tested, but looking at the code for the attributewriter
https://github.com/fruux/sabre-xml-atom/blob/master/lib/Service.php#L39
it seems `$value` is not defined (copied from attributereader?) should it be `$object` ?

**Comment by evert** [comment]
Yep you are right. This package is unfortunately a bit under-tested. I'll add a few unittests today and fix this bug as well.

**Comment by evert** [comment]
This bug is fixed. looking into the source I sort of found out that while the parsing system works well, writing atom was in a pretty bad shape and had a number of bugs.

I fixed all those bugs, added some unittests and released sabre/xml 1.4.0 for the bugs that had to be fixed in that package. I'll release 0.1.0 of this package shortly.
